### ISSUE TITLE
Only non GPS activities data export?

### ISSUE THREAD

**Issue by Uwe-B** [tomato4/Amazfit_sportdata_exporter#1]
I thought this is an interesting app but trying it, it didn't export any activities on my Amazfit pace, since (my guess) all activities I did are GPS based activities. I think that should be mentioned in the README.md file.

**Comment by glazrtom** [comment]
Yes, this app only exports non GPS workouts, because workouts with GPS can watch export directly by button in workouts history. But for sports without GPS, you have no choice to export them.

And yes i forgot to mention that in readme. Sorry about that.
